@startuml
skinparam ObjectShadowing false

skinparam object {
    BackgroundColor White
    BorderColor Black
    FontColor Black
    FontName Arial
    ArrowColor Black
    ArrowStyle Straight
}


object VkPipeline

object VkShaderModule

object VkDeviceMemory

object VkPipelineLayout {
    descriptorSetLayouts[]
}

object VkDescriptorSetLayout {
    descriptorSetLayoutBindings[]
}

object VkDescriptorSetLayoutBinding {
    binding
    descriptorType = VK_DESCRIPTOR_TYPE_TENSOR_ARM
}

object VkDataGraphPipelineSessionARM {
    pipeline
}

object VkDataGraphPipelineConstantARM {
    next = VkDataGraphPipelineResourceInfoARM
    id
}

object VkDataGraphPipelineConstantTensorARM {
    tensorDescription
    data
}

object VkDataGraphPipelineResourceInfoARM {
    next = VkDataGraphPipelineResourceInfoTensorARM
    descriptorSet
    binding
}

object VkDataGraphPipelineResourceInfoTensorARM {
    tensorDescription
}

object VkDescriptorSet {
    descriptorSetLayouts[]
}

object VkWriteDescriptorSet {
    next = VkWriteDescriptorSetTensorARM
    type = VK_DESCRIPTOR_TYPE_TENSOR_ARM
    binding
}

object VkWriteDescriptorSetTensorARM {
    tensorView
}

object VkTensorViewARM {
    tensor
    format
}

object VkTensorARM {
    tensorDescription
}

object VkTensorDescriptionARM {
    tiling
    format
    dimensions[]
    strides[]
}

object VkCommandBuffer

VkCommandBuffer --> VkDataGraphPipelineSessionARM
VkCommandBuffer --> VkPipeline
VkCommandBuffer --> VkPipelineLayout

VkDataGraphPipelineSessionARM --> VkPipeline
VkDataGraphPipelineSessionARM -> VkDeviceMemory

VkDescriptorSet --> VkWriteDescriptorSet
    VkWriteDescriptorSet --> VkWriteDescriptorSetTensorARM
        VkWriteDescriptorSetTensorARM --> VkTensorViewARM
            VkTensorViewARM --> VkTensorARM
                VkTensorARM --> VkTensorDescriptionARM
VkDescriptorSet --> VkDescriptorSetLayout

VkPipeline --> VkShaderModule
VkPipeline --> VkPipelineLayout
    VkPipelineLayout --> VkDescriptorSetLayout
        VkDescriptorSetLayout --> VkDescriptorSetLayoutBinding
VkPipeline --> VkDataGraphPipelineConstantARM
    VkDataGraphPipelineConstantARM --> VkDataGraphPipelineConstantTensorARM
        VkDataGraphPipelineConstantTensorARM --> VkTensorDescriptionARM
VkPipeline --> VkDataGraphPipelineResourceInfoARM
    VkDataGraphPipelineResourceInfoARM --> VkDataGraphPipelineResourceInfoTensorARM
        VkDataGraphPipelineResourceInfoTensorARM --> VkTensorDescriptionARM

@enduml
